import streamlit as st

# ================== AI Text Detector App ==================

st.set_page_config(page_title="AI Text Detector", page_icon="🤖", layout="centered")

st.title("AI Text Detector")
st.write("Check if a text was written by a human or generated by AI.")

# Input box with large text area
user_input = st.text_area("Enter a sentence or paragraph:", height=200, placeholder="Type or paste your text here...")

# Show a button to analyze
if st.button("Scan") and user_input.strip():
    # ======= Add your model and detection logic here =======

    import math

    # --- Your dataset goes here (I'll assume you've added the data list above already) ---
    data = [
        ("She enjoys visiting new cafes around the city.", 0),
        ("We went bowling with some friends last weekend.", 0),
        ("He spent the day at the beach, reading a book.", 0),
        # (Add the rest of your data here, or load from file)
    ]

    texts, labels = zip(*data)

    def preprocess(text):
        text = text.lower()
        text = "".join(char for char in text if char.isalpha() or char.isspace())
        return text

    def tokenize(text):
        return text.split()

    vocab = set()
    for text in texts:
        tokens = tokenize(preprocess
